# Generated by Django 5.1.3 on 2025-01-09 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counseloruser',
            name='password',
            field=models.CharField(max_length=3000),
        ),
    ]
