# Generated by Django 5.1.3 on 2025-01-16 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselor', '0002_alter_counseloruser_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='introduction',
            field=models.TextField(blank=True, null=True),
        ),
    ]
