# Generated by Django 5.1.5 on 2025-01-18 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselor', '0003_chapter_introduction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursecontentprogress',
            name='content_id',
        ),
        migrations.AddField(
            model_name='coursecontentprogress',
            name='part_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='counselor.part'),
        ),
    ]
