# Generated by Django 5.1.5 on 2025-01-18 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselor', '0004_remove_coursecontentprogress_content_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounselorCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_code', models.CharField(blank=True, max_length=8, null=True)),
                ('grade', models.CharField(blank=True, max_length=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='counselor.counseloruser')),
            ],
        ),
    ]
