# Generated by Django 5.1.5 on 2025-01-18 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counselor', '0005_counselorcertification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='introduction',
        ),
    ]
