# Generated by Django 5.1.5 on 2025-03-11 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselor', '0006_remove_chapter_introduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresults',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='counselor.counselorcourse'),
        ),
    ]
