# Generated by Django 5.1.5 on 2025-04-08 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselor', '0007_quizresults_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseOverviewPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.TextField(blank=True, null=True)),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='points', to='counselor.chapter')),
            ],
        ),
    ]
