# Generated by Django 5.1.5 on 2025-04-08 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselor', '0008_courseoverviewpoints'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseOverviewSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.TextField(blank=True, null=True)),
                ('title2', models.TextField(blank=True, null=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='summarys', to='counselor.counselorcourse')),
            ],
        ),
    ]
