# Generated by Django 5.1.5 on 2025-04-09 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counselor', '0010_userprogresstrack'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userprogresstrack',
            unique_together={('user', 'course')},
        ),
    ]
