# Generated by Django 5.1.5 on 2025-04-10 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselor', '0011_alter_userprogresstrack_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='index',
            field=models.IntegerField(default=0),
        ),
    ]
