# Generated by Django 5.1.5 on 2025-04-29 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselor', '0012_chapter_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='index',
            field=models.IntegerField(default=0),
        ),
    ]
