# Generated by Django 5.1.5 on 2025-04-29 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselor', '0013_part_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuizAttemptTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_attempt', models.IntegerField(default=0)),
                ('window_closed_time', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='counselor.counselorcourse')),
                ('part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='counselor.part')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='counselor.counseloruser')),
            ],
            options={
                'unique_together': {('user', 'course', 'part')},
            },
        ),
    ]
