# Generated by Django 5.1.5 on 2025-05-08 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselor', '0014_userquizattempttrack'),
    ]

    operations = [
        migrations.AddField(
            model_name='counselorcertification',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='counselor.counselorcourse'),
        ),
    ]
