# Generated by Django 5.1.5 on 2025-05-08 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counselor', '0015_counselorcertification_course'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='counselorcertification',
            unique_together={('user', 'course')},
        ),
    ]
