# Generated by Django 4.2.23 on 2026-03-13 10:55

import counselor.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counselor', '0016_alter_counselorcertification_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(blank=True, default='INR', max_length=10)),
                ('gateway_receipt', models.CharField(blank=True, max_length=120, null=True)),
                ('gateway_order_id', models.CharField(blank=True, max_length=120, null=True)),
                ('gateway_payment_id', models.CharField(blank=True, max_length=120, null=True)),
                ('gateway_signature', models.CharField(blank=True, max_length=120, null=True)),
                ('is_success', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Course payments',
                'ordering': ('-created',),
            },
        ),
        migrations.AddField(
            model_name='counselorcourse',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Course price in INR. 0 or null = free.', max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='PaymentReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(blank=True, max_length=120)),
                ('invoice_number', models.CharField(blank=True, max_length=64)),
                ('invoice_pdf', models.FileField(blank=True, null=True, upload_to=counselor.models.payment_receipt_upload_to)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='counselor.coursepayment')),
            ],
            options={
                'verbose_name_plural': 'Payment receipts',
            },
        ),
        migrations.AddField(
            model_name='coursepayment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='counselor.counselorcourse'),
        ),
        migrations.AddField(
            model_name='coursepayment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_payments', to='counselor.counseloruser'),
        ),
    ]
