# Generated by Django 4.2.23 on 2026-03-13 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counselor', '0017_add_price_and_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursepayment',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='DiscountCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=64, unique=True)),
                ('discount_type', models.CharField(choices=[('percent', 'Percentage'), ('fixed', 'Fixed amount')], default='percent', max_length=20)),
                ('value', models.DecimalField(decimal_places=2, help_text='Percentage (e.g. 10) or fixed amount in INR', max_digits=10)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='Leave blank for unlimited', null=True)),
                ('times_used', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, help_text='Leave blank for all courses', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='counselor.counselorcourse')),
            ],
            options={
                'verbose_name_plural': 'Discount coupons',
                'ordering': ('-created',),
            },
        ),
        migrations.AddField(
            model_name='coursepayment',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='counselor.discountcoupon'),
        ),
    ]
