# Generated by Django 4.2.23 on 2026-03-13 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counselor', '0018_discount_coupon_and_paid_ribbon'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTrialStart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trial_starts', to='counselor.counselorcourse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_trials', to='counselor.counseloruser')),
            ],
            options={
                'verbose_name_plural': 'Course trial starts',
                'unique_together': {('user', 'course')},
            },
        ),
    ]
