# Generated by Django 4.2.23 on 2026-03-14 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselor', '0019_course_trial_start'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=80, unique=True)),
                ('value', models.CharField(help_text='Display text for this label', max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Site labels (buttons, ribbons)',
                'ordering': ('key',),
            },
        ),
    ]
